app/models/order.rb, app/models/product.rb, app/models/review.rb
Have done validations for reviews, orders and products. 
Fixed some issues related to length
=> Validations

app/controllers/products_controller.rb, app/models/user.rb, app/views/pages/edit.html.erb, app/views/pages/new.html.erb, app/views/products/index.html.erb, config/routes.rb, db/migrate/20200602020204_add_price_to_products.rb
error in migrate about column repetition in regards to email(users model). Once fixed we need to migrate: 
1) price to product model
2) rating to review model (rating mandatory, description not)
3) picture to product model
=> Products views

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/passwords/edit.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
problem solved when creating a new user instance throught simple form, problem was due to the strong parameters and the validation.
=> signing up problem fixed

app/assets/stylesheets/components/_banner.scss
putting the banner on the right place, was breaking after i pulled everything down 80px in all views pages.
=> Fixing the dislocated banner

app/controllers/application_controller.rb, app/controllers/pages_controller.rb
=> Authentication and authorization

public/422.html
Changed the bg color from EFEFEF to EFEFE0
=> change bg color

db/migrate/20200602161718_add_rating_to_reviews.rb, db/schema.rb
Added rating to rewiew and price to product
=> added rating to review model

app/models/user.rb, app/views/products/show.html.erb
updated and still working on show
=> Migration product

app/controllers/products_controller.rb, app/controllers/users_controller.rb, app/policies/product_policy.rb, app/policies/user_policy.rb, app/views/products/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, config/routes.rb, test/controllers/users_controller_test.rb
still have to create the button so the user can create new products, so far so good
=> Usercontroller

app/views/products/show.html.erb
Fixed no review error and added review count too
=> fixed no rieviews crash

app/controllers/application_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb
registration views updated to ask to see if the user wants to be a seller.
=> Updated the registrations view.

app/controllers/products_controller.rb, app/views/pages/home.html.erb, app/views/products/edit.html.erb, app/views/products/new.html.erb, config/routes.rb
fixed the price to show in the card, forms, edit views and strong parameters for the products.
=> Updatingproductsform

app/views/users/show.html.erb
Fixed route error when pressing my profile in navbar
=> fixed route error

app/controllers/users_controller.rb, app/javascript/components/banner.js, app/javascript/plugins/init_mapbox.js, app/views/users/show.html.erb
fixing Js for every page putting a condition in the Type.Js logic, fixed the initmapbox logic to work with an array, fixed the show page.
=> Fixing JS problems.

app/controllers/orders_to_products_controller.rb, app/models/order.rb, app/models/product.rb, app/models/user.rb, app/policies/orders_to_product_policy.rb, app/views/products/show.html.erb, config/routes.rb, test/policies/orders_to_product_policy_test.rb
Added add to cart feature missing authentication 
added routes orders-to-products controller 
added policy orders-to-products
fixed problem in user model and product model (has_many)
implemented a little of front end in product show page :)
=> Add to cart

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/javascript/components/banner.js, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, app/views/products/show.html.erb
Navbar is not great, i am following the advise of Pedro, i prefer to stick with the old one.
Took out the text decoration of the cards in the home page.
Fixed the style of the form in the signup view, going to do the others.
Made the cards i little less uglier, we have to discuss something in the brieffing about these.
=> Hotfixviews

app/assets/stylesheets/components/_form.scss, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/products/edit.html.erb, app/views/products/new.html.erb, app/views/reviews/new.html.erb
Fixed all the forms putting them in a containner.
=> fixing all the forms

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/controllers/users_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/users/_info_window.html.erb
Map, good to go now, our logo was the marker and zooming in.
=> Improvingmap

app/policies/user_policy.rb, app/views/products/show.html.erb
created the icon for the edit and edit is only show if the person is the one selling that product
=> Edit for Product is done, with authentication.

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_searchform.scss, app/controllers/pages_controller.rb, app/models/product.rb, app/views/pages/home.html.erb
=> Searchform

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_products_show.scss, app/views/products/show.html.erb
implemented more css to product show page
=> Frontend show

config/routes.rb
Created all the cart logic, the views, and created a table to show the cart, cheers.
=> adding to orders show to the routes

app/controllers/orders_controller.rb, app/controllers/orders_to_products_controller.rb, app/views/orders/show.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, test/controllers/orders_controller_test.rb
=> solving git issues

app/controllers/orders_controller.rb, app/policies/order_policy.rb, app/views/orders/show.html.erb, config/routes.rb
setting up the pay logic, patch http request method with redirection …to the user profile page
=> pay button done.

app/assets/stylesheets/components/_form.scss, app/controllers/orders_controller.rb, app/controllers/orders_to_products_controller.rb, app/policies/orders_to_product_policy.rb, app/views/orders/show.html.erb
created the logic for method: delete in the chart, put the icon as a …button, updated the policy
=> delete option in the chart is done.

app/controllers/orders_to_products_controller.rb, app/views/shared/_navbar.html.erb
trying to create the logic of the link, code in comments, will ask to…morrow for help
=> No changes, just comment to comeback tomorrow to fix it.

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_banner.scss, app/views/orders/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
- banner was not strechting to all the page, fixed that.
- putted the chart icon in the navbar, instead of my orders
=> Ajaxtodelete

app/assets/stylesheets/components/_card.scss
making 4cards in a row in desktop, 3 in tablets and 1 in mobile
=> fixing the cards row.

app/assets/stylesheets/components/_form.scss, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
=> Stylyingedivise

app/assets/stylesheets/config/_bootstrap_variables.scss
change the size of General Style from 1rem to 2rem
=> Change the Banner Size Letter

app/assets/stylesheets/components/_form.scss, app/views/orders/show.html.erb
added some style to cart shopping
=> styling cart css

app/assets/stylesheets/pages/_products_show.scss, app/assets/stylesheets/pages/_users_show.scss, app/models/order.rb, app/views/products/show.html.erb, app/views/users/show.html.erb, db/seeds.rb
Updated seed so we can have more products with appropriate pictures and reviews 
**to see this remember to do rails db:seed**
working on users front end this isnt the final version its still a working progress
=> Product show page

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_searchform.scss, app/views/orders/show.html.erb
=> updated the chart and similars

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_searchform.scss, app/views/orders/show.html.erb, app/views/products/new.html.erb, app/views/users/show.html.erb
make the background picture of the divise part more cool.
=> Fixingstyle

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_product.scss, app/views/products/show.html.erb
put everything inside of a box and made a little better the products page
=> made the product page a little bit less ugly.

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/config/_fonts.scss, app/views/orders/show.html.erb
=> Style button

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_product.scss
=> hover functionality
